### ISSUE TITLE
Gradle 9.0 deprecation warning for forUseAtConfigurationTime

### ISSUE THREAD

**Issue by shashachu** [runningcode/gradle-doctor#313]
We're seeing this warning during build config time:

```
The Provider.forUseAtConfigurationTime method has been deprecated.	
This is scheduled to be removed in Gradle 9.0.	
Simply remove the call.	
[Documentation](https://docs.gradle.org/8.4/userguide/upgrading_version_7.html#for_use_at_configuration_time_deprecation)	
1 usage	
Plugin:com.osacky.doctor	
at org.gradle.api.internal.provider.AbstractMinimalProvider.forUseAtConfigurationTime(AbstractMinimalProvider.java:135)	
at com.osacky.doctor.internal.CoCaHelpersKt.sysProperty(CoCaHelpers.kt:15)	
at com.osacky.doctor.KotlinCompileDaemonFallbackDetector.isDaemonDisabled(KotlinCompileDaemonFallbackDetector.kt:65)	
at com.osacky.doctor.KotlinCompileDaemonFallbackDetector.onStart(KotlinCompileDaemonFallbackDetector.kt:25)	
at com.osacky.doctor.DoctorPlugin$apply$1.execute(DoctorPlugin.kt:71)	
at com.osacky.doctor.DoctorPlugin$apply$1.execute(DoctorPlugin.kt:35)
```

**Comment by runningcode** [comment]
What version of the Gradle Doctor are you using?
