### ISSUE TITLE
Make Gradle Doctor Compatible with the configuration cache

### ISSUE THREAD

**Issue by runningcode** [runningcode/gradle-doctor#71]
https://docs.gradle.org/release-nightly/userguide/configuration_cache.html

**Comment by ZacSweers** [comment]
```
- plugin 'com.osacky.doctor': registration of listener on 'Gradle.buildFinished' is unsupported
  See https://docs.gradle.org/6.6-rc-6/userguide/configuration_cache.html#config_cache:requirements:build_listeners
```

**Comment by ZacSweers** [comment]
```
at com.osacky.doctor.BuildOperations.<init>(BuildOperations.kt:55)
	at com.osacky.doctor.DoctorPlugin.apply(DoctorPlugin.kt:35)
	at com.osacky.doctor.DoctorPlugin.apply(DoctorPlugin.kt:21)
```

**Comment by ZacSweers** [comment]
```
at com.osacky.doctor.DoctorPlugin.apply(DoctorPlugin.kt:51)
	at com.osacky.doctor.DoctorPlugin.apply(DoctorPlugin.kt:21)
```

**Comment by runningcode** [comment]
The message says that it was not able to recognize the plugin. If you try configuration cache in a build, it should work fine with Gradle Doctor. If not could you please upload the configuration cache report html?

**Comment by ColtonIdle** [comment]
@runningcode that's my mistake for misinterpreting that message. Just trying to be proactive. Sorry for bothering you with it. Cheers
